set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(AARCH64_NONE_ELF "${CMAKE_CURRENT_LIST_DIR}/../third_party/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-")
set(CMAKE_C_COMPILER   "${AARCH64_NONE_ELF}gcc")
set(CMAKE_CXX_COMPILER "${AARCH64_NONE_ELF}g++")
set(CMAKE_ASM_COMPILER "${AARCH64_NONE_ELF}gcc")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
